#!/usr/bin/env ruby

begin
  require 'nokogiri'
rescue LoadError
  abort <<-MSG
Unable to load nokogiri.
  Ensure you have it installed and/or
  export RUBYOPT=rubygems
  MSG
end

require 'open-uri'
require 'stringio'
require 'pp'

DefaultWSDL = "http://s3.amazonaws.com/ec2-downloads/2008-02-01.ec2.wsdl"

wsdl_url = ARGV.shift || DefaultWSDL
Wsdl = Nokogiri::XML.parse(open(wsdl_url))

##__END__

list_keys = []
item_types = Wsdl.search(%Q|//xs:complexType//xs:element[@name="item"]|)
item_types.each do |item_type|
  ns, name = item_type["type"].split(":")
  next if ns != "tns"
  complex = item_type.parent.parent
  uses = Wsdl.search(%Q|//xs:element[@type="#{ns}:#{complex["name"]}"]|)
  uses.each do |u|
    list_keys << u["name"]
  end
end

pp list_keys.uniq
